// Generated by tools/build_habitats.py from data/habitat_db.xlsx — do not edit by hand.
window.HABITAT_DB = {
 "regions": [
  {
   "id": "stavropol",
   "ru": "Ставропольский край",
   "zh": "斯塔夫罗波尔边疆区",
   "en": "Stavropol Krai",
   "country": "RU",
   "bbox": [
    40.8,
    43.6,
    45.8,
    46.3
   ],
   "note": "Границы — по bbox субъекта РФ; уточнить при необходимости"
  },
  {
   "id": "bolshoy_khingan",
   "ru": "Большой Хинган",
   "zh": "大兴安岭",
   "en": "Greater Khingan",
   "country": "CN",
   "bbox": [
    119.5,
    46.0,
    126.0,
    53.6
   ],
   "note": "Китайская часть хребта (Внутренняя Монголия, Хэйлунцзян)"
  },
  {
   "id": "maly_khingan",
   "ru": "Малый Хинган",
   "zh": "小兴安岭",
   "en": "Lesser Khingan",
   "country": "CN",
   "bbox": [
    126.0,
    46.5,
    131.0,
    50.3
   ],
   "note": "Хэйлунцзян: Ичунь, Хэйхэ, Хэган"
  },
  {
   "id": "eastern_mountains",
   "ru": "Восточные горы",
   "zh": "东部山地",
   "en": "Eastern Mountains (Heilongjiang)",
   "country": "CN",
   "bbox": [
    128.0,
    43.3,
    135.1,
    47.5
   ],
   "note": "Чжангуанцайлин, Лаоелин, Ваньдашань, северный Чанбайшань"
  }
 ],
 "categories": [
  {
   "id": 1,
   "ru": "Леса",
   "def_ru": "территории, покрытые кронами древесной и древесно-кустарниковой растительности более чем на 20% площади и с высотой растений более 5 м",
   "zh": "森林"
  },
  {
   "id": 2,
   "ru": "Молодняки и кустарники",
   "def_ru": "территории, покрытые кронами древесной и древесно-кустарниковой растительности более чем на 20% площади и с высотой растений до 5 м",
   "zh": "幼林与灌丛"
  },
  {
   "id": 3,
   "ru": "Тундры",
   "def_ru": "безлесные территории приполярных областей,расположенные за северными пределами лесной растительности, а также территории с вечномерзлой почвой, не заливаемые морскими или речными водами",
   "zh": "苔原"
  },
  {
   "id": 4,
   "ru": "Болота",
   "def_ru": "территории, постоянно большую часть года избыточно насыщенные водой и покрытые специфической гигрофитной растительностью",
   "zh": "沼泽"
  },
  {
   "id": 5,
   "ru": "Лугово-степные комплексы",
   "def_ru": "территории,занятые многолетней мезофитной и ксерофитной травянистой растительностью",
   "zh": "草甸草原复合体"
  },
  {
   "id": 6,
   "ru": "Альпийские луга",
   "def_ru": "территории,занятые высокогорной растительностью, расположенные за верхними пределами лесов",
   "zh": "高山草甸"
  },
  {
   "id": 7,
   "ru": "Пустыни и камни",
   "def_ru": "территории,покрытые растительностью менее чем на 20% площади. К данной категории также относят солончаки, ледники, скалы и каменистые россыпи без растительности",
   "zh": "荒漠与裸岩"
  },
  {
   "id": 8,
   "ru": "Сельхозугодья",
   "def_ru": "территории, вовлеченные в сельскохозяйственный оборот - пашни (в т.ч. заливные), залежи, сенокосы",
   "zh": "农业用地"
  },
  {
   "id": 9,
   "ru": "Внутренние водные объекты",
   "def_ru": "все акватории водотоков (рек,ручьев, мелиоративных каналов), озер, прудов и водохранилищ",
   "zh": "内陆水体"
  },
  {
   "id": 10,
   "ru": "Пойменные комплексы",
   "def_ru": "территории, затопляемые в период половодья водотоков, находящиеся между среднестатистическим минимальным и максимальным урезами воды, в том числе покрытые древесно-кустарниковой растительностью",
   "zh": "河漫滩复合体"
  },
  {
   "id": 11,
   "ru": "Береговые комплексы",
   "def_ru": "периодически затапливаемые прибрежные территории (в том числе приливно-отливные) озер, прудов, водохранилищ, морей и океанов, находящиеся между среднестатистическим минимальным и максимальным урезами воды, а также мелководные участки этих водных объектов, занятые прикрепленной надводной гигрофитной растительностью",
   "zh": "滨岸复合体"
  },
  {
   "id": 12,
   "ru": "Преобразованные и поврежденные участки",
   "def_ru": "леса, поврежденные пожарами (гари), территории ветровалов,торфоразработок, участки с нарушенным почвенным покровом в результате добычи полезных ископаемых и других техногенных воздействий",
   "zh": "受扰动与受损地段"
  },
  {
   "id": 13,
   "ru": "Непригодные для ведения охотничьего хозяйства",
   "def_ru": "территории, занятые населенными пунктами, промышленными комплексами,рудеральные территории (свалки, кладбища и др.)",
   "zh": "不适于狩猎经营的区域"
  }
 ],
 "classes": [
  {
   "id": 11,
   "cat": 1,
   "ru": "Хвойные вечнозеленые (хвойных вечнозеленых пород более 80%)",
   "zh": "常绿针叶林"
  },
  {
   "id": 12,
   "cat": 1,
   "ru": "Хвойные листопадные (хвойных листопадных пород более 80%)",
   "zh": "落叶针叶林"
  },
  {
   "id": 13,
   "cat": 1,
   "ru": "Мелколиственные (мелколиственных пород более 80%)",
   "zh": "小叶林（桦、杨）"
  },
  {
   "id": 14,
   "cat": 1,
   "ru": "Широколиственные (широколиственных пород более 30%)",
   "zh": "阔叶林"
  },
  {
   "id": 15,
   "cat": 1,
   "ru": "Смешанные с преобладанием хвойных пород (хвойных пород 60 - 80%)",
   "zh": "针叶占优混交林"
  },
  {
   "id": 16,
   "cat": 1,
   "ru": "Смешанные с преобладанием мелколиственных пород (мелколиственных пород 60 - 80%)",
   "zh": "小叶占优混交林"
  },
  {
   "id": 17,
   "cat": 1,
   "ru": "Смешанные с присутствием широколиственных пород (широколиственных пород менее 30%)",
   "zh": "含阔叶树种的混交林"
  },
  {
   "id": 18,
   "cat": 1,
   "ru": "Искусственно созданные (кроме посадок на месте вырубок)",
   "zh": "人工林"
  },
  {
   "id": 21,
   "cat": 2,
   "ru": "Вырубки и зарастающие поля",
   "zh": "采伐迹地与撂荒地"
  },
  {
   "id": 22,
   "cat": 2,
   "ru": "Вечнозеленые кустарники, в т.ч. высокогорные",
   "zh": "常绿灌丛（含高山）"
  },
  {
   "id": 23,
   "cat": 2,
   "ru": "Лиственные кустарники",
   "zh": "落叶灌丛"
  },
  {
   "id": 31,
   "cat": 3,
   "ru": "Кустарничковые",
   "zh": "小灌木苔原"
  },
  {
   "id": 32,
   "cat": 3,
   "ru": "Кустарниковые",
   "zh": "灌木苔原"
  },
  {
   "id": 33,
   "cat": 3,
   "ru": "Моховые,лишайниковые и травянистые",
   "zh": "藓类、地衣与草本苔原"
  },
  {
   "id": 34,
   "cat": 3,
   "ru": "Заболоченная тундра",
   "zh": "沼泽化苔原"
  },
  {
   "id": 41,
   "cat": 4,
   "ru": "Верховые",
   "zh": "高位沼泽"
  },
  {
   "id": 42,
   "cat": 4,
   "ru": "Травяные",
   "zh": "草本沼泽"
  },
  {
   "id": 43,
   "cat": 4,
   "ru": "Трясины",
   "zh": "浮毡沼泽"
  },
  {
   "id": 51,
   "cat": 5,
   "ru": "Луга",
   "zh": "草甸"
  },
  {
   "id": 52,
   "cat": 5,
   "ru": "Степи",
   "zh": "草原"
  },
  {
   "id": 61,
   "cat": 6,
   "ru": "Полностью покрытые травой (камней, лесов или кустарников до 20%)",
   "zh": "全草被高山草甸"
  },
  {
   "id": 62,
   "cat": 6,
   "ru": "Высокогорные и с каменистыми россыпями (камней до 80%)",
   "zh": "高山碎石草甸"
  },
  {
   "id": 71,
   "cat": 7,
   "ru": "Горы без растительности",
   "zh": "无植被山地"
  },
  {
   "id": 72,
   "cat": 7,
   "ru": "Ледники",
   "zh": "冰川"
  },
  {
   "id": 73,
   "cat": 7,
   "ru": "Пустыни",
   "zh": "荒漠"
  },
  {
   "id": 81,
   "cat": 8,
   "ru": "Пашни",
   "zh": "耕地"
  },
  {
   "id": 82,
   "cat": 8,
   "ru": "Луга сельскохозяйственного назначения (сенокосы и пастбища)",
   "zh": "割草地与牧场"
  },
  {
   "id": 83,
   "cat": 8,
   "ru": "Заливные пашни",
   "zh": "水田"
  },
  {
   "id": 91,
   "cat": 9,
   "ru": "Водотоки",
   "zh": "河流与溪流"
  },
  {
   "id": 92,
   "cat": 9,
   "ru": "Водохранилища",
   "zh": "水库"
  },
  {
   "id": 93,
   "cat": 9,
   "ru": "Озера, пруды",
   "zh": "湖泊与池塘"
  },
  {
   "id": 101,
   "cat": 10,
   "ru": "С преобладанием леса (лес более 80%)",
   "zh": "以森林为主的河漫滩"
  },
  {
   "id": 102,
   "cat": 10,
   "ru": "С преобладанием травянистой растительности (лес и кустарники до 20%)",
   "zh": "以草本为主的河漫滩"
  },
  {
   "id": 103,
   "cat": 10,
   "ru": "Смешанный лесной",
   "zh": "河漫滩混交林"
  },
  {
   "id": 104,
   "cat": 10,
   "ru": "Смешанный кустарниковый",
   "zh": "河漫滩混合灌丛"
  },
  {
   "id": 111,
   "cat": 11,
   "ru": "Береговой комплекс внутренних водных объектов",
   "zh": "内陆水体滨岸带"
  },
  {
   "id": 112,
   "cat": 11,
   "ru": "Береговой комплекс внешних водных объектов",
   "zh": "海岸带"
  },
  {
   "id": 121,
   "cat": 12,
   "ru": "Преобразованные и поврежденные участки (гари,торфоразработки,ветровалы и др.)",
   "zh": "受扰动与受损地段（火烧迹地、风倒、泥炭采掘等）"
  },
  {
   "id": 131,
   "cat": 13,
   "ru": "Промышленные и рудеральные комплексы, населенные пункты и др.",
   "zh": "工业、荒废地与居民点"
  }
 ],
 "habitats": [
  {
   "region": "bolshoy_khingan",
   "class": 11,
   "type": 1,
   "ru": "Сосновые леса",
   "zh": "樟子松林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Pine forest)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 12,
   "type": 1,
   "ru": "Лиственничные с берёзой",
   "zh": "落叶松占优的落叶松白桦林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Larch-dominated larch–birch forest)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 12,
   "type": 2,
   "ru": "Лиственничные редколесья",
   "zh": "落叶松疏林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Sparse larch woodland)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 12,
   "type": 3,
   "ru": "Заболоченные редколесья",
   "zh": "沼泽化疏林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Waterlogged open woodlands)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 13,
   "type": 1,
   "ru": "Заболоченные берёзово-ивовые леса",
   "zh": "沼泽化白桦柳林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Paludified birch–willow forest)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 13,
   "type": 2,
   "ru": "Берёзовые леса без лиственницы",
   "zh": "无落叶松混生的桦木林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Birch forests without larch)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 13,
   "type": 3,
   "ru": "Каменноберёзовые леса и криволесья",
   "zh": "岳桦林及岳桦矮曲林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Stone-birch forests and krummholz)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 14,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 62858.0,
   "share_pct": 0.95,
   "community": "Грабово-ясеневые дубравы — наиболее распространённый тип дубовых лесов Ставропольской возвышенности. Также встречаются свежие ясенево-грабовые дубравы, пакленовые дубравы, свежие дубово-грабовые бучины (Fagus orientalis) и свежие кленово-грабовые ясеневники (у г. Стрижамент). Выделено 43 типа леса, основа — 525 геоботанических описаний (2005–2012 гг.)",
   "source": "Шевченко Н.Е., Викторов В.П. Леса Центрального Предкавказья // Вестник ТГУ. 2014. Т. 19, вып. 5. С. 1622–1625. PDF; Шевченко Н.Е. // Вопросы лесной науки. 2019. Т. 2, № 1. DOI 10.31509/2658-607x-2019-2-1-1-26 (jfsi.ru)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 15,
   "type": 1,
   "ru": "Берёзово-лиственничные с примерно равными долями",
   "zh": "白桦与落叶松共优林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Codominant birch–larch forest)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 15,
   "type": 2,
   "ru": "Берёзово-темнохвойные смешанные леса",
   "zh": "桦木与云冷杉混交林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Mixed birch–spruce–fir forests)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 16,
   "type": 1,
   "ru": "Берёзовые с лиственницей",
   "zh": "白桦占优的白桦落叶松林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Birch-dominated birch–larch forest)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 17,
   "type": 1,
   "ru": "Дубово-мелколиственные леса",
   "zh": "蒙古栎及阔叶混交林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Oak and oak–small-leaved forest)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 18,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 70255.0,
   "share_pct": 1.06,
   "community": "Полезащитные лесополосы (Грачёвский, Изобильненский, Кочубеевский, Шпаковский р-ны). Травяной покров представлен сорными модификациями: пырейно-разнотравной (ОПП 70–100%, высота 60–110 см), кострецово-пырейной (ОПП 90–100%), мятликово-разнотравной (ОПП 100%) и др. Воздушно-сухая масса — 13,6–20,6 ц/га. В лесополосах тополя чёрного доминируют Amaranthus retroflexus, Ambrosia artemisiifolia, Bromus japonicus, Chenopodium album, Cirsium arvense",
   "source": "Дудченко Л.В., Лапенко Н.Г., Дружинин В.А. Эколого-флористическая ситуация объектов лесомелиорации в агроландшафтах Ставропольского края. DOI 10.12737/article_5967e9653fc089.77407015 (naukaru.ru); Дудченко Л.В. // Достижения науки и техники АПК. 2012. № 7 (КиберЛенинка)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 18,
   "type": 1,
   "ru": "Лесокультуры",
   "zh": "人工林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Forest plantation)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 21,
   "type": 1,
   "ru": "Молодняки на вырубках",
   "zh": "采伐迹地幼林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Young stands on clear-cuts)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 22,
   "type": 1,
   "ru": "Заросли кедрового стланика",
   "zh": "偃松灌丛",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Siberian dwarf pine scrub)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 23,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 16231.0,
   "share_pct": 0.25,
   "community": "Кустарниковые подлески и опушки байрачных и низкогорных лесов: Prunus spinosa, Crataegus monogyna, Acer campestre, Pyrus caucasica. В степях кустарники входят как компоненты асс. Teucrio chamaedris-Stipetum pulcherrimae",
   "source": "Шевченко, 2019 (jfsi.ru); Лысенко Т.М. и др. // Russian Journal of Ecosystem Ecology. 2023. 8(2). DOI 10.21685/2500-0578-2023-2-4 (rjee.ru)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 23,
   "type": 1,
   "ru": "Шибляк",
   "zh": "旱生灌丛",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Xeric shrub thicket (shibliak))",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 41,
   "type": 1,
   "ru": "Верховые болота",
   "zh": "高位沼泽（贫营养）",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Raised bog)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 42,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 6593.0,
   "share_pct": 0.1,
   "community": "Тростниковая формация Phragmiceta australis, сообщества Phragmites australis — экотоны «вода–суша» Кумо-Манычской впадины (Калмыкия, смежно с краем). В крае отмечены заросли тростника южного в хвостовой части Чограйского водохранилища",
   "source": "Горяев И.А., Уланова С.С. // Ботанический журнал. 2023. Т. 108, № 9. С. 844–853. DOI 10.31857/S0006813623090053 (sciencejournals.ru)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 42,
   "type": 1,
   "ru": "Низинные болота",
   "zh": "低位沼泽（富营养）",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Minerotrophic fen)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 42,
   "type": 2,
   "ru": "Субальпийские травяные болота",
   "zh": "亚高山草本沼泽",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Subalpine herbaceous wetlands)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 43,
   "type": 1,
   "ru": "Переходные болота",
   "zh": "中营养沼泽（过渡沼泽）",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Transitional mire)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 51,
   "type": 1,
   "ru": "Закустаренные луга",
   "zh": "灌丛化草甸",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Shrub-encroached meadow)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 73,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 141037.0,
   "share_pct": 2.13,
   "community": "Полупустынные пастбища востока края (Курский, Левокумский, Нефтекумский, Степновский р-ны). Встречаются полынная и однолетниково-полынная модификации (Artemisia lerchiana, A. austriaca, Poa bulbosa, Aegilops cylindrica, Bromus mollis), а также разнотравно-ковыльная (Stipa lessingiana, Agropyron desertorum). Урожайность — 4,2–9,0 ц/га сухой массы",
   "source": "Лапенко Н.Г., Старостина М.А., Костицын Р.Д. // Аграрный вестник Урала. 2025. Т. 25, № 5. С. 690–702. DOI 10.32417/1997-4868-2025-25-05-690-702 (PDF); Лапенко Н.Г. и др. // там же. 2024. Т. 24, № 9. DOI 10.32417/1997-4868-2024-24-09-1128-1137 (PDF)"
  },
  {
   "region": "stavropol",
   "class": 81,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 1628487.0,
   "share_pct": 24.61,
   "community": "Пастбищные бородачёвые степи: бородачёвое (Bothriochloa ischaemum, ОПП 90%), ковыльно-бородачёвое (B. ischaemum – Stipa lessingiana, ОПП 95%), разнотравно-ковыльное (Stipa pennata – Herbae stepposae, ОПП 95%). Бешпагирские высоты, 16 учётных площадок, 185 видов. Асс. по Лапенко: «овсяница валлисская + ковыль Лессинга + тысячелистник щетинистый» (Маки, ОПП 80%)",
   "source": "Белоус В.Н., Лыхварь А.В. // Samara Journal of Science. 2020. Т. 9, № 4. С. 23–33. DOI 10.17816/snv202094103 (snv63.ru); Лапенко и др., 2020 (PDF)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 81,
   "type": 1,
   "ru": "Агрокультуры",
   "zh": "农田",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Cropland)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 82,
   "type": 1,
   "ru": "Пастбищные луга",
   "zh": "放牧草地",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Grazed pasture)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 91,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 18592.0,
   "share_pct": 0.28,
   "community": "",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 91,
   "type": 1,
   "ru": "Русла и урезы",
   "zh": "河道与河滩",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: River channels and bars)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 92,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 16507.0,
   "share_pct": 0.25,
   "community": "",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 93,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 57732.0,
   "share_pct": 0.87,
   "community": "",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 101,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 15805.0,
   "share_pct": 0.24,
   "community": "Сырой пойменный тополевый (Populus alba, P. nigra), влажный и свежий пойменные дубово-тополевые (с Quercus robur, Ulmus minor), сырой пойменный ивовый груд, сероольховый груд (Alnus incana), черноольховый сугрудок (Alnus glutinosa). Поймы Кубани, Кумы, Подкумка, Терека",
   "source": "Шевченко, Викторов, 2014 (PDF)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 101,
   "type": 1,
   "ru": "Пойменные и околоводные мелколиственные леса",
   "zh": "河漫滩与近水阔叶林",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Floodplain and riparian small-leaved forest)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 102,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 33785.0,
   "share_pct": 0.51,
   "community": "Долина р. Егорлык: полидоминантные разнотравно-злаковые сообщества (Achillea millefolium, Agropyron pectinatum, Poa angustifolia, Medicago romanica, Thalictrum minus), ОПП 100%, три подъяруса (110–120, 60–70, 25–30 см). Луговидные сообщества с Elytrigia repens, E. elongata, Glycyrrhiza glabra",
   "source": "Белоус В.Н. // Проблемы ботаники Южной Сибири и Монголии. 2020. Т. 19, № 2. С. 264–268. DOI 10.14258/pbssm.2020116 (PDF)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 102,
   "type": 1,
   "ru": "Пойменные луга",
   "zh": "河漫滩草甸",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Floodplain meadow)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 111,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 9010.0,
   "share_pct": 0.14,
   "community": "Берег оз. Солёное (Медвежинское): гемигалофитные бедноразнотравные мелкодерновинно-злаковые сообщества Festuca valesiaca + Agropyron pectinatum (с Limonium platyphyllum, Artemisia pontica, Galatella villosa) на засолённых грунтах. Галофитные формации соседних манычских озёр: Halocnemeta strobilacei, Suaedeta acuminatae, Tamariceta laxae",
   "source": "Белоус, 2020 (PDF); Горяев, Уланова, 2023 (sciencejournals.ru)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 121,
   "type": 1,
   "ru": "Постпирогенные сообщества",
   "zh": "火烧迹地群落",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Post-fire communities)",
   "source": ""
  },
  {
   "region": "stavropol",
   "class": 131,
   "type": null,
   "ru": "",
   "zh": "",
   "area_ha": 356487.0,
   "share_pct": 5.39,
   "community": "Пустыри и промежуточные стадии вторичных сукцессий: Elytrigia repens, Cichorium intybus, Convolvulus arvensis, Amaranthus retroflexus, Urtica dioica, Solidago canadensis (Западный Кавказ и Ставропольская возвышенность, 155 проб). Пырейные сообщества пустырей с Calamagrostis epigeios (ОПП 98–100%, Ростов-на-Дону)",
   "source": "Акатов В.В. и др. // Экология. 2019. № 5. С. 332–340. DOI 10.1134/S0367059719040036 (sciencejournals.ru); Литвинская С.А. и др. // Юг России: экология, развитие. 2023. Т. 18, № 3. DOI 10.18470/1992-1098-2023-3-69-80 (PDF)"
  },
  {
   "region": "bolshoy_khingan",
   "class": 131,
   "type": 1,
   "ru": "Рудеральные луга",
   "zh": "杂草（人为干扰）植被",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Ruderal vegetation)",
   "source": ""
  },
  {
   "region": "bolshoy_khingan",
   "class": 131,
   "type": 2,
   "ru": "Застройка и промзоны",
   "zh": "建设用地与工业用地",
   "area_ha": null,
   "share_pct": null,
   "community": "(англ.: Built-up and industrial land)",
   "source": ""
  }
 ]
};
